version: "3.2"
services:

  php-cartorio:
    container_name: php-apache
    image: php:7.2
    build:
      context: .docker
    volumes:
      - ./:/var/www/html/
    ports:
      - "8081:80"
    depends_on:
      - mysql-cartorio
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    networks:
      - development-network

  mysql-cartorio:
    image: mysql:5.7
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=cartorio"
      - "MYSQL_USER=developer"
      - "MYSQL_PASSWORD=developer"
      - "MYSQL_ROOT_PASSWORD=developer"
    ports:
      - "33061:3306"
    networks:
      - development-network

networks:
  development-network: